action: publish: add check if configured branches exist
If the configuration has misspelled or changed branches, the job should
fail.

Signed-off-by: Stefan Müller-Klieser <s.mueller-klieser@phytec.de>

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -26,6 +26,13 @@ jobs:
       run: |
         branches=( $BRANCHES )
         for i in "${branches[@]}"; do
+          # check if configured branch exists
+          ret=$(git branch | grep -w "${branches[$i]}")
+          if [ $? -gt 0 ]; then
+            echo "ERROR: expected branch ${branches[$i]} does not exist in local clone!"
+            exit 1
+          fi
+
           echo "syncing branch $i"
           git checkout -B $i origin/$i
           git push origin --follow-tags HEAD:$i
